language: node_js
sudo: true
node_js: stable
cache:
  directories:
  - node_modules
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_047d2e62ea22_key -iv $encrypted_047d2e62ea22_iv -in .env.enc -out .env -d || true'
script:
- npm test
env:
  global:
  - CF_APP=conversation-simple
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=appgallery
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
  - cf-blue-green-travis
  on:
    branch: release
    repo: watson-developer-cloud/conversation-simple
  skip_cleanup: true
